version: '3.2'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"
  logstash:
    build: ./logstash
    links:
      - "redis"
  elasticsearch:
    image: "elasticsearch:alpine"
    ports:
      - "127.0.0.1:9200:9200"
